[package]
name = "controlplane-core"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
thiserror = { workspace = true }
tonic = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
