[package]
name = "server"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
controlplane-core = { path = "../core" }
domain = { path = "../domain" }
infra-db = { path = "../infra-db" }
infra-stripe = { path = "../infra-stripe" }
infra-kube = { path = "../infra-kube" }
infra-spicedb = { path = "../infra-spicedb" }
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
jsonwebtoken = { workspace = true }
moka = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
base64 = { workspace = true }
rsa = { workspace = true }
rand = { workspace = true }

[build-dependencies]
tonic-prost-build = "0.14"
